export interface CityData {
  slug: string;
  name: string;
  county: string;
  state: string;
  population: string;
  description: string;
  descriptionEs: string;
  localDetail: string;
  localDetailEs: string;
  nearbyCity: string;
  nearbyCityEs: string;
  landmark: string;
  landmarkEs: string;
}

export const cities: CityData[] = [
  {
    slug: "atlanta",
    name: "Atlanta",
    county: "Fulton & DeKalb County",
    state: "GA",
    population: "500,000+",
    description: "Atlanta's urban canopy, heavy rainfall, and high humidity make exterior cleaning a necessity for homeowners and businesses alike. From Buckhead estates to Midtown condos, we keep Atlanta looking its best.",
    descriptionEs: "El dosel urbano de Atlanta, las lluvias frecuentes y la alta humedad hacen que la limpieza exterior sea una necesidad para propietarios y negocios. Desde las mansiones de Buckhead hasta los condominios de Midtown, mantenemos Atlanta en su mejor estado.",
    localDetail: "From Grant Park bungalows to Sandy Springs estates, Atlanta's diverse housing stock faces constant challenges from pollen, humidity, and Georgia clay. Our team knows every neighborhood.",
    localDetailEs: "Desde los bungalows de Grant Park hasta las mansiones de Sandy Springs, las casas de Atlanta enfrentan desafíos constantes del polen, la humedad y la arcilla de Georgia.",
    nearbyCity: "Lawrenceville & Decatur",
    nearbyCityEs: "Lawrenceville y Decatur",
    landmark: "Buckhead, Midtown, Inman Park",
    landmarkEs: "Buckhead, Midtown, Inman Park",
  },
  {
    slug: "lawrenceville",
    name: "Lawrenceville",
    county: "Gwinnett County",
    state: "GA",
    population: "30,000+",
    description: "As Gwinnett County's seat, Lawrenceville is home to beautiful subdivisions and growing commercial areas. We're your local pressure washing experts — based right here in Lawrenceville.",
    descriptionEs: "Como sede del Condado de Gwinnett, Lawrenceville alberga hermosas subdivisiones y áreas comerciales en crecimiento. Somos tus expertos locales en lavado a presión, con base aquí mismo en Lawrenceville.",
    localDetail: "Lawrenceville neighborhoods like Sugarloaf Country Club, Hamilton Mill, and Flowers Crossing trust Altitude Service Solutions for their exterior cleaning needs. We're your neighbors.",
    localDetailEs: "Los vecindarios de Lawrenceville como Sugarloaf Country Club, Hamilton Mill y Flowers Crossing confían en Altitude Service Solutions para sus necesidades de limpieza exterior. Somos tus vecinos.",
    nearbyCity: "Duluth & Buford",
    nearbyCityEs: "Duluth y Buford",
    landmark: "Sugarloaf Pkwy, Hwy 316",
    landmarkEs: "Sugarloaf Pkwy, Hwy 316",
  },
  {
    slug: "duluth",
    name: "Duluth",
    county: "Gwinnett County",
    state: "GA",
    population: "28,000+",
    description: "Duluth's upscale neighborhoods and thriving business district demand the best in exterior maintenance. Our pressure washing and soft washing services keep Duluth properties looking like new.",
    descriptionEs: "Los elegantes vecindarios de Duluth y su próspero distrito comercial exigen lo mejor en mantenimiento exterior. Nuestros servicios mantienen las propiedades de Duluth luciendo como nuevas.",
    localDetail: "From the prestigious communities near Sugarloaf Country Club to the commercial corridors along Pleasant Hill Road, Duluth properties benefit from regular exterior cleaning in Georgia's climate.",
    localDetailEs: "Desde las prestigiosas comunidades cerca de Sugarloaf Country Club hasta los corredores comerciales a lo largo de Pleasant Hill Road, las propiedades de Duluth se benefician de la limpieza exterior regular.",
    nearbyCity: "Norcross & Lawrenceville",
    nearbyCityEs: "Norcross y Lawrenceville",
    landmark: "Sugarloaf Country Club, Pleasant Hill Rd",
    landmarkEs: "Sugarloaf Country Club, Pleasant Hill Rd",
  },
  {
    slug: "norcross",
    name: "Norcross",
    county: "Gwinnett County",
    state: "GA",
    population: "16,000+",
    description: "Norcross blends historic charm with modern growth. Our exterior cleaning services serve Norcross homeowners and businesses throughout this vibrant Gwinnett community.",
    descriptionEs: "Norcross combina el encanto histórico con el crecimiento moderno. Nuestros servicios de limpieza exterior sirven a propietarios y negocios de Norcross en toda esta vibrante comunidad de Gwinnett.",
    localDetail: "Norcross's historic district and newer residential developments both benefit from regular soft washing and pressure washing to combat Georgia's humidity and pollen.",
    localDetailEs: "El distrito histórico de Norcross y los nuevos desarrollos residenciales se benefician del lavado regular para combatir la humedad y el polen de Georgia.",
    nearbyCity: "Duluth & Peachtree Corners",
    nearbyCityEs: "Duluth y Peachtree Corners",
    landmark: "Historic Downtown Norcross, I-85",
    landmarkEs: "Centro Histórico de Norcross, I-85",
  },
  {
    slug: "buford",
    name: "Buford",
    county: "Gwinnett & Hall County",
    state: "GA",
    population: "16,000+",
    description: "Buford's rapid growth and beautiful Lake Lanier area properties make exterior maintenance essential. We serve Buford's residential and commercial properties with professional pressure washing and soft washing.",
    descriptionEs: "El rápido crecimiento de Buford y las hermosas propiedades del área del lago Lanier hacen que el mantenimiento exterior sea esencial. Servimos a las propiedades residenciales y comerciales de Buford.",
    localDetail: "Lake Lanier's proximity means Buford homes face extra challenges from moisture and algae. Our soft washing service is especially effective at eliminating lake-area biological growth.",
    localDetailEs: "La proximidad al lago Lanier significa que las casas de Buford enfrentan desafíos adicionales de humedad y algas. Nuestro servicio de soft washing es especialmente efectivo para eliminar el crecimiento biológico del área del lago.",
    nearbyCity: "Suwanee & Gainesville",
    nearbyCityEs: "Suwanee y Gainesville",
    landmark: "Lake Lanier, Mall of Georgia",
    landmarkEs: "Lago Lanier, Mall of Georgia",
  },
  {
    slug: "suwanee",
    name: "Suwanee",
    county: "Gwinnett County",
    state: "GA",
    population: "20,000+",
    description: "Consistently ranked among the best places to live in Georgia, Suwanee homeowners take pride in their properties. Our exterior cleaning services help Suwanee homes maintain their award-winning appearance.",
    descriptionEs: "Constantemente clasificada entre los mejores lugares para vivir en Georgia, los propietarios de Suwanee se enorgullecen de sus propiedades. Nuestros servicios de limpieza exterior ayudan a mantener la apariencia de primer nivel de las casas de Suwanee.",
    localDetail: "Suwanee's highly-rated neighborhoods like Olde Atlanta Club, Roberts' Landing, and Seven Seas trust Altitude Service Solutions to maintain their homes' pristine appearance.",
    localDetailEs: "Los vecindarios de alto nivel de Suwanee como Olde Atlanta Club, Roberts' Landing y Seven Seas confían en Altitude Service Solutions para mantener la apariencia impecable de sus hogares.",
    nearbyCity: "Duluth & Buford",
    nearbyCityEs: "Duluth y Buford",
    landmark: "Suwanee Town Center, Olde Atlanta Club",
    landmarkEs: "Suwanee Town Center, Olde Atlanta Club",
  },
  {
    slug: "peachtree-corners",
    name: "Peachtree Corners",
    county: "Gwinnett County",
    state: "GA",
    population: "45,000+",
    description: "Georgia's first planned city and a hub of innovation, Peachtree Corners combines upscale residential communities with a thriving tech corridor. We keep this city's premier properties looking their best year-round.",
    descriptionEs: "La primera ciudad planificada de Georgia y un centro de innovación, Peachtree Corners combina comunidades residenciales de lujo con un próspero corredor tecnológico. Mantenemos las propiedades de esta ciudad en su mejor estado durante todo el año.",
    localDetail: "From the prestigious neighborhoods surrounding Technology Park Atlanta to the executive homes near Simpsonwood, Peachtree Corners properties demand top-tier exterior maintenance. Georgia's pollen and humidity are no match for our professional cleaning systems.",
    localDetailEs: "Desde los prestigiosos vecindarios alrededor de Technology Park Atlanta hasta las casas ejecutivas cerca de Simpsonwood, las propiedades de Peachtree Corners exigen un mantenimiento exterior de primer nivel.",
    nearbyCity: "Norcross & Duluth",
    nearbyCityEs: "Norcross y Duluth",
    landmark: "Technology Park, Curiosity Lab, Wesleyan School",
    landmarkEs: "Technology Park, Curiosity Lab, Wesleyan School",
  },
  {
    slug: "sugar-hill",
    name: "Sugar Hill",
    county: "Gwinnett County",
    state: "GA",
    population: "25,000+",
    description: "Sugar Hill is one of Gwinnett's most vibrant growing cities, with a charming downtown district and beautiful residential communities. Our exterior cleaning services help Sugar Hill homeowners maintain their property values.",
    descriptionEs: "Sugar Hill es una de las ciudades de más rápido crecimiento de Gwinnett, con un encantador centro y hermosas comunidades residenciales. Nuestros servicios ayudan a los propietarios de Sugar Hill a mantener el valor de sus propiedades.",
    localDetail: "Sugar Hill's newer subdivisions and established neighborhoods alike benefit from regular exterior cleaning to combat Georgia's year-round pollen, humidity, and biological growth on driveways and siding.",
    localDetailEs: "Los nuevos desarrollos y los vecindarios establecidos de Sugar Hill se benefician de la limpieza exterior regular para combatir el polen, la humedad y el crecimiento biológico de Georgia durante todo el año.",
    nearbyCity: "Buford & Suwanee",
    nearbyCityEs: "Buford y Suwanee",
    landmark: "Downtown Sugar Hill, E-Force Field",
    landmarkEs: "Downtown Sugar Hill, E-Force Field",
  },
  {
    slug: "snellville",
    name: "Snellville",
    county: "Gwinnett County",
    state: "GA",
    population: "22,000+",
    description: "Snellville is a well-established Gwinnett community with a mix of classic homes and newer developments. From the Shiloh area to Snellville Towne Center, we serve homeowners and businesses throughout the city.",
    descriptionEs: "Snellville es una comunidad establecida de Gwinnett con una mezcla de hogares clásicos y nuevos desarrollos. Desde el área de Shiloh hasta Snellville Towne Center, servimos a propietarios y negocios en toda la ciudad.",
    localDetail: "Snellville's mature tree canopy and established neighborhoods create ideal conditions for algae, mold, and mildew on driveways, roofs, and siding. Our professional soft washing and pressure washing services restore and protect your home's exterior.",
    localDetailEs: "El dosel arbóreo maduro y los vecindarios establecidos de Snellville crean condiciones ideales para el crecimiento de algas, moho y hongos. Nuestros servicios restauran y protegen el exterior de su hogar.",
    nearbyCity: "Loganville & Lilburn",
    nearbyCityEs: "Loganville y Lilburn",
    landmark: "Snellville Towne Center, Shiloh Rd",
    landmarkEs: "Snellville Towne Center, Shiloh Rd",
  },
  {
    slug: "dacula",
    name: "Dacula",
    county: "Gwinnett County",
    state: "GA",
    population: "8,000+",
    description: "Dacula is one of Gwinnett's fastest-growing communities, with beautiful new construction homes and established neighborhoods. We provide professional exterior cleaning to help Dacula homeowners protect their investment.",
    descriptionEs: "Dacula es una de las comunidades de más rápido crecimiento de Gwinnett, con hermosas casas de nueva construcción y vecindarios establecidos. Proporcionamos limpieza exterior profesional para ayudar a los propietarios de Dacula a proteger su inversión.",
    localDetail: "From the communities near Harbins Road to the subdivisions along Hwy 316, Dacula's new and established homes benefit from regular exterior maintenance. New construction accumulates dust and biological growth quickly in Georgia's climate.",
    localDetailEs: "Desde las comunidades cerca de Harbins Road hasta las subdivisiones a lo largo de la Hwy 316, los hogares de Dacula se benefician del mantenimiento exterior regular. La construcción nueva acumula rápidamente suciedad y crecimiento biológico en el clima de Georgia.",
    nearbyCity: "Buford & Lawrenceville",
    nearbyCityEs: "Buford y Lawrenceville",
    landmark: "Harbins Park, Hwy 316",
    landmarkEs: "Harbins Park, Hwy 316",
  },
  {
    slug: "lilburn",
    name: "Lilburn",
    county: "Gwinnett County",
    state: "GA",
    population: "12,000+",
    description: "Lilburn is a diverse and welcoming Gwinnett community with a charming Old Town district and established residential neighborhoods. We're proud to serve Lilburn homeowners and businesses with professional exterior cleaning.",
    descriptionEs: "Lilburn es una comunidad diversa y acogedora de Gwinnett con un encantador distrito Old Town y vecindarios residenciales establecidos. Estamos orgullosos de servir a los propietarios y negocios de Lilburn con limpieza exterior profesional.",
    localDetail: "Old Town Lilburn's historic homes and the community's established subdivisions along Camp Creek Pkwy benefit from regular soft washing to maintain curb appeal and protect siding, brick, and roofing from Georgia's biological growth.",
    localDetailEs: "Las casas históricas de Old Town Lilburn y las subdivisiones establecidas se benefician del soft washing regular para mantener el atractivo exterior y proteger el revestimiento, el ladrillo y los techos.",
    nearbyCity: "Norcross & Snellville",
    nearbyCityEs: "Norcross y Snellville",
    landmark: "Old Town Lilburn, Camp Creek Pkwy",
    landmarkEs: "Old Town Lilburn, Camp Creek Pkwy",
  },
  {
    slug: "loganville",
    name: "Loganville",
    county: "Walton & Gwinnett County",
    state: "GA",
    population: "12,000+",
    description: "Loganville sits at the edge of Gwinnett and Walton counties, offering a blend of suburban convenience and small-town charm. Our professional pressure washing and soft washing services keep Loganville properties looking their best.",
    descriptionEs: "Loganville se encuentra en el límite de los condados Gwinnett y Walton, ofreciendo una combinación de comodidad suburbana y encanto de ciudad pequeña. Nuestros servicios mantienen las propiedades de Loganville en su mejor estado.",
    localDetail: "Loganville's growing community spans both Gwinnett and Walton counties, with a mix of newer subdivisions and established homes. Regular exterior cleaning protects property values and removes the biological growth that Georgia's climate accelerates year-round.",
    localDetailEs: "La creciente comunidad de Loganville abarca los condados de Gwinnett y Walton, con una mezcla de nuevas subdivisiones y hogares establecidos. La limpieza exterior regular protege el valor de las propiedades y elimina el crecimiento biológico.",
    nearbyCity: "Snellville & Grayson",
    nearbyCityEs: "Snellville y Grayson",
    landmark: "Loganville Town Center, Hwy 78",
    landmarkEs: "Loganville Town Center, Hwy 78",
  },
  {
    slug: "alpharetta",
    name: "Alpharetta",
    county: "Fulton County",
    state: "GA",
    population: "68,000+",
    description: "Alpharetta is one of Georgia's premier cities — home to Fortune 500 tech offices, the upscale Avalon district, and some of the area's most beautiful residential communities. Our services meet the high standards Alpharetta homeowners expect.",
    descriptionEs: "Alpharetta es una de las principales ciudades de Georgia, hogar de oficinas tecnológicas Fortune 500, el exclusivo distrito Avalon y algunas de las comunidades residenciales más hermosas del área. Nuestros servicios cumplen con los altos estándares que esperan los propietarios de Alpharetta.",
    localDetail: "From the executive estates near Country Club of the South to the beautiful neighborhoods surrounding the Avalon district, Alpharetta properties represent significant investments that deserve professional exterior maintenance. We serve all Alpharetta neighborhoods with pride.",
    localDetailEs: "Desde las fincas ejecutivas cerca del Country Club of the South hasta los hermosos vecindarios alrededor del distrito Avalon, las propiedades de Alpharetta representan inversiones significativas que merecen un mantenimiento exterior profesional.",
    nearbyCity: "Johns Creek & Cumming",
    nearbyCityEs: "Johns Creek y Cumming",
    landmark: "Avalon, Downtown Alpharetta, GA-400",
    landmarkEs: "Avalon, Downtown Alpharetta, GA-400",
  },
  {
    slug: "johns-creek",
    name: "Johns Creek",
    county: "Fulton County",
    state: "GA",
    population: "84,000+",
    description: "Johns Creek is consistently ranked among the safest and most desirable cities in Georgia. With prestigious planned communities and executive-level properties, Johns Creek homeowners trust Altitude for their exterior cleaning needs.",
    descriptionEs: "Johns Creek está clasificada constantemente entre las ciudades más seguras y deseables de Georgia. Con prestigiosas comunidades planificadas y propiedades ejecutivas, los propietarios de Johns Creek confían en Altitude para sus necesidades de limpieza exterior.",
    localDetail: "The prestigious communities of Johns Creek — including Country Club of the South, St. Ives, and Medlock Bridge — represent some of Georgia's finest homes. Our professional soft washing and pressure washing services are trusted by Johns Creek's most discerning homeowners.",
    localDetailEs: "Las prestigiosas comunidades de Johns Creek, incluyendo Country Club of the South, St. Ives y Medlock Bridge, representan algunos de los hogares más exclusivos de Georgia. Nuestros servicios son de confianza para los propietarios más exigentes de Johns Creek.",
    nearbyCity: "Alpharetta & Duluth",
    nearbyCityEs: "Alpharetta y Duluth",
    landmark: "Country Club of the South, St. Ives, Emory Johns Creek",
    landmarkEs: "Country Club of the South, St. Ives, Emory Johns Creek",
  },
  {
    slug: "cumming",
    name: "Cumming",
    county: "Forsyth County",
    state: "GA",
    population: "8,000+",
    description: "Cumming is the seat of Forsyth County — one of Georgia's fastest-growing counties — and offers beautiful homes near Lake Lanier and the thriving Cumming City Center. We serve Cumming homeowners and businesses with pride.",
    descriptionEs: "Cumming es la sede del Condado de Forsyth, uno de los condados de más rápido crecimiento de Georgia, y ofrece hermosas casas cerca del lago Lanier. Servimos a los propietarios y negocios de Cumming con orgullo.",
    localDetail: "Forsyth County's explosive growth means many Cumming neighborhoods feature newer homes that still need regular maintenance to combat Georgia's mold, mildew, and pollen. Lake Lanier proximity also adds moisture challenges that our soft washing addresses perfectly.",
    localDetailEs: "El explosivo crecimiento del Condado de Forsyth significa que muchos vecindarios de Cumming tienen casas más nuevas que aún necesitan mantenimiento regular para combatir el moho y el polen de Georgia. La proximidad al lago Lanier agrega desafíos de humedad.",
    nearbyCity: "Alpharetta & Buford",
    nearbyCityEs: "Alpharetta y Buford",
    landmark: "Lake Lanier, Cumming City Center, GA-400",
    landmarkEs: "Lago Lanier, Cumming City Center, GA-400",
  },
  {
    slug: "gainesville",
    name: "Gainesville",
    county: "Hall County",
    state: "GA",
    population: "45,000+",
    description: "Known as the Poultry Capital of the World, Gainesville is the economic hub of Hall County and the Lake Lanier area. We bring professional exterior cleaning services to Gainesville's residential and commercial properties.",
    descriptionEs: "Conocida como la Capital Mundial de las Aves de Corral, Gainesville es el centro económico del Condado de Hall y el área del Lago Lanier. Llevamos servicios profesionales de limpieza exterior a las propiedades de Gainesville.",
    localDetail: "Gainesville's lakefront properties, established neighborhoods, and commercial districts all benefit from regular professional cleaning. The Lake Lanier area's humidity creates ideal conditions for algae and mold growth that our soft washing eliminates safely and effectively.",
    localDetailEs: "Las propiedades frente al lago, los vecindarios establecidos y los distritos comerciales de Gainesville se benefician de la limpieza profesional regular. La humedad del área del Lago Lanier crea condiciones ideales para el crecimiento de algas y moho.",
    nearbyCity: "Buford & Cumming",
    nearbyCityEs: "Buford y Cumming",
    landmark: "Lake Lanier, Downtown Gainesville, Brenau University",
    landmarkEs: "Lago Lanier, Downtown Gainesville, Universidad Brenau",
  },
];

export function getCity(slug: string): CityData | undefined {
  return cities.find((c) => c.slug === slug);
}
